-- =================================================================
-- Script para la Creación de Todas las Tablas del Sistema
-- Este script define la estructura completa de la base de datos.
-- =================================================================

-- 1. Tabla de Rutas
CREATE TABLE IF NOT EXISTS public.routes (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    origin character varying(100) NOT NULL,
    destination character varying(100) NOT NULL,
    duration_minutes integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    created_at timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT routes_pkey PRIMARY KEY (id)
);

-- 2. Tabla de Horarios (Frecuencias)
CREATE TABLE IF NOT EXISTS public.schedules (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    route_id uuid NULL,
    departure_time time without time zone NOT NULL,
    days_of_week integer[] NOT NULL,
    is_active boolean NULL,
    created_at timestamp without time zone NULL DEFAULT now(),
    CONSTRAINT schedules_pkey PRIMARY KEY (id),
    CONSTRAINT schedules_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id) ON DELETE CASCADE
);

-- 3. Tabla de Buses
CREATE TABLE IF NOT EXISTS public.buses (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    capacity integer NULL DEFAULT 40,
    bus_number character varying NULL,
    route_id uuid NULL,
    is_active boolean NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT buses_pkey PRIMARY KEY (id),
    CONSTRAINT buses_bus_number_key UNIQUE (bus_number),
    CONSTRAINT buses_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id) ON UPDATE CASCADE
);

-- 4. Tabla de Pasajeros
CREATE TABLE IF NOT EXISTS public.passengers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying NULL,
    email character varying NULL,
    phone character varying NULL,
    address text NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    identification character varying NULL,
    CONSTRAINT passengers_pkey PRIMARY KEY (id),
    CONSTRAINT passengers_identification_key UNIQUE (identification)
);

-- 5. Tabla de Viajes (Trips)
CREATE TABLE IF NOT EXISTS public.trips (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    schedule_id uuid NULL,
    trip_date date NOT NULL,
    available_seats integer NULL DEFAULT 40,
    status character varying(20) NULL DEFAULT 'active'::character varying,
    created_at timestamp without time zone NULL DEFAULT now(),
    bus_id bigint NULL,
    CONSTRAINT trips_pkey PRIMARY KEY (id),
    CONSTRAINT trips_bus_id_fkey FOREIGN KEY (bus_id) REFERENCES public.buses(id) ON UPDATE CASCADE,
    CONSTRAINT trips_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id) ON DELETE CASCADE
);

-- 6. Tabla de Reservas
CREATE TABLE IF NOT EXISTS public.reservations (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    trip_id uuid NULL,
    passenger_id bigint NOT NULL,
    passenger_name character varying(200) NOT NULL,
    passenger_email character varying(100) NOT NULL,
    passenger_phone character varying(20) NOT NULL,
    passenger_address text NULL,
    seat_numbers integer[] NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    payment_status character varying(20) NULL DEFAULT 'pending'::character varying,
    payment_method character varying(50) NULL,
    confirmation_code character varying(10) NULL,
    created_at timestamp without time zone NULL DEFAULT now(),
    notes text NULL,
    CONSTRAINT reservations_pkey PRIMARY KEY (id),
    CONSTRAINT reservations_confirmation_code_key UNIQUE (confirmation_code),
    CONSTRAINT reservations_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES public.passengers(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT reservations_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE
);

-- 7. Tabla de Asientos
CREATE TABLE IF NOT EXISTS public.seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trip_id uuid NULL,
    seat_number integer NULL,
    is_reserved boolean NULL,
    reservation_id uuid NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT seats_pkey PRIMARY KEY (id),
    CONSTRAINT seats_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT seats_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON UPDATE CASCADE
);

-- 8. Tabla de Pagos
CREATE TABLE IF NOT EXISTS public.payments (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    reservation_id uuid NULL,
    amount numeric(10, 2) NOT NULL,
    payment_method character varying(50) NOT NULL,
    transaction_id character varying(100) NULL,
    receipt_url character varying(500) NULL,
    status character varying(20) NULL DEFAULT 'pending'::character varying,
    created_at timestamp without time zone NULL DEFAULT now(),
    card_last_four text NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT payments_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id) ON DELETE CASCADE
);
